### ISSUE TITLE
Server used for this project

### ISSUE THREAD

**Issue by aqilrryn** [rafvanpuyvelde/my-valorant-store#1]
Does this project only works for accounts in NA servers. I tried logging in using my Asia Pacific account and it showed incorrect store results

**Comment by rafvanpuyvelde** [comment]
It unfortunately only works for European users, this is because I use the EU-based endpoint (you can pick the endpoint based on your location see: /api/src/services/rsoService.ts from line:169). I suggest forking the repository and modifying the endpoint URL if needed (since I have no plans to continue this project). I hope this answers your question.
